### PR TITLE
added some stuff to tutorial

### PR DESCRIPTION
**Pull request by elamdf**
Changes some stuff in the tutorial- see comments on the .rmd file. Should we make a separate one for statistical tests / graphing stuff? I feel like that might be good so we can make them discrete lessons. Let me know!

### CODE REVIEW

**Comment by nickfong** [comment]
`here` takes care of the path issues for us – assuming this is run from within the repo, there's no need to change directories, etc.

Everything else LGTM

**Comment by nickfong** [comment]
Actually wait I take back the LGTM.  `country_codes` won't be defined with your edits

**Comment by nickfong** [comment]
So maybe the intent wasn't clear here:  The tutorial goes over how to take the actual country names (which aren't in `allmerged.xlsx`) and adds them to the merged data.  This is in response to the question yesterday that Vien asked about what country corresponded to the high GDP-low mortality data point

Edit:  I dropped a `)`

**Comment by elamdf** [comment]
oh ok makes sense, is everything else good? I think teaching about the working directory is important, feel free to move the set/ get wd commands to wherever you want them. Creating figures might be a good place to introduce that concept so they can write out the image files to their desktop or something like that.

**Pull request closed without merging**
